0.18 debugger
fbonetti/ruby-elm-compiler pull request #6
Opened 2017-01-25 00:18 UTC by nvaldes

Enables the elm debugger if environment is not production.

2017-01-28 01:47 UTC, lsimoneau requested changes
I put in one comment on the code. If you can address that and also squash this into a single commit it looks 👍

2017-01-28 01:47 UTC, lsimoneau commented on lib/elm/compiler.rb
> +          Open3.popen3({"LANG" => "en_US.UTF8" }, elm_make_path, *elm_files, '--yes', '--output', output_path) do |_stdin, _stdout, stderr, wait_thr|
I think you could avoid a lot of this duplication by doing something like:

```
args = [{"LANG" => "en_US.UTF8" }, elm_make_path, *elm_files, '--yes', '--output', output_path]
args << "--debug" if debug
```

And then calling `popen3` with `args`.

2017-01-29 06:21 UTC, nvaldes commented
@lsimoneau Thanks, didn't know you could * an array to use it as args.

How do I squash this into to one commit?  I tried to rebase-merge onto master but it doesn't seem to have worked.  I can still the the 7 individual commits in my fork.

2017-02-04 00:00 UTC, lsimoneau commented
@nvaldes Thanks for squashing. Generally you'd want to reword the commit message so it only includes stuff that's relevant to someone looking back at the history and trying to figure out why things were done the way they were. In this case I'm happy to fix up the commit and sort it out.

I'm just waiting on @fbonetti to grant me access to this repo so I can push the updated commit and get it merged in.

2017-02-10 04:27 UTC, lsimoneau commented
I just reworded your commit message here: https://github.com/fbonetti/ruby-elm-compiler/pull/7 but merging now.

2017-02-10 04:27 UTC, closed without merging